rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/Gemfile-activemodel-3.1.x
  - gemfiles/Gemfile-activemodel-3.2.x
  - gemfiles/Gemfile-activemodel-4.0.x
  - gemfiles/Gemfile-activemodel-4.1.x
  - gemfiles/Gemfile-activemodel-4.2.x
  - gemfiles/Gemfile-activemodel-5.0.x
  - gemfiles/Gemfile-activemodel-5.1.x
  - gemfiles/Gemfile-activemodel-5.2.x
  - gemfiles/Gemfile-activemodel-6.0.x
matrix:
  exclude:
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile-activemodel-6.0.x
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile-activemodel-6.0.x
    - rvm: 2.4.6
      gemfile: gemfiles/Gemfile-activemodel-4.1.x
    - rvm: 2.4.6
      gemfile: gemfiles/Gemfile-activemodel-4.2.x
    - rvm: 2.4.6
      gemfile: gemfiles/Gemfile-activemodel-6.0.x
    - rvm: 2.5.5
      gemfile: gemfiles/Gemfile-activemodel-4.1.x
    - rvm: 2.5.5
      gemfile: gemfiles/Gemfile-activemodel-4.2.x
    - rvm: 2.6.3
      gemfile: gemfiles/Gemfile-activemodel-4.1.x
    - rvm: 2.6.3
      gemfile: gemfiles/Gemfile-activemodel-4.2.x
sudo: false
