rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/Gemfile-activemodel-3.0.x
  - gemfiles/Gemfile-activemodel-3.1.x
  - gemfiles/Gemfile-activemodel-3.2.x
  - gemfiles/Gemfile-activemodel-4.0.x
  - gemfiles/Gemfile-activemodel-4.1.x
  - gemfiles/Gemfile-activemodel-4.2.x
  - gemfiles/Gemfile-activemodel-5.0.x
exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile-activemodel-5.0.x
  - rvm: 2.0.0
    gemfile: gemfiles/Gemfile-activemodel-5.0.x
  - rvm: 2.1.8
    gemfile: gemfiles/Gemfile-activemodel-5.0.x
sudo: false
